title: printf("Hello, world! I'm Sacha Manson-Smith")
description: > # this means to ignore newlines until "baseurl:"
  A random collection of things that I find interesting
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sacha Manson-Smith
author-img: sacha.png
about-author: Software developer, cyclist. Lives with Type 1 diabetes.
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: sachams
social-linkedin: smansonsmith
social-email: # add your Email address

# Disqus
discus-identifier: sachams

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
